---
title: "Dental Data Pack"
subtitle: "`r params$region_STP_name`"
date: "`r paste(format(Sys.time(), '%B, %Y'), ' - Reporting up to end of', format(Sys.Date() - lubridate::weeks(4), '%B, %Y'))`"
output:
  xaringan::moon_reader:
    css: [theme.css, nhsr-fonts.css]
    self_contained: true
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
params:
  level: "National"
  region_STP_name: NULL
---


```{r setup, include=FALSE}

library(tidyverse)
library(readxl)
library(DBI)
library(odbc)
library(reactable) #make sure you have the latest version by doing install.packages("reactable")
library(downloadthis)
source("../R/03 SMT_plot_functions.R")
source("../R/02 format_SMT_data.R")

#pull data from NCDR
UDA_calendar_data <- pull_UDA_calendar_data()
UOA_calendar_data <- pull_UOA_calendar_data()
UDA_scheduled_data <- pull_UDA_scheduled_data()
UOA_scheduled_data <- pull_UOA_scheduled_data()

historical_UDA_scheduled_data <- pull_UDA_scheduled_historical_data()

#change column names and add regions
UDA_calendar_data <- rename(UDA_calendar_data, month = data_month)
UOA_calendar_data <- UOA_calendar_data %>%
  rename(month = data_month) %>%
  mutate(contract_number = as.numeric(contract_number),
         UOA_total = as.numeric(UOA_total)) 
    #add a region column to the data
    region_STP_lookup <- UDA_calendar_data %>%
      select(contract_number, name_or_company_name, commissioner_name, region_name) %>%
      distinct()
    
    UOA_calendar_data <- left_join(UOA_calendar_data, region_STP_lookup, by = c("contract_number", "name_or_company_name", "commissioner_name"))
UDA_scheduled_data <- rename(UDA_scheduled_data, month = data_month)
UOA_scheduled_data <- rename(UOA_scheduled_data, month = data_month)

#Read local 111 file
dental_data_111 <- read_excel("N:/_Everyone/Primary Care Group/SMT_Dental/raw_eDEN_dental_data/111_pathways_data/dental_data_111.xls")

#############still to fix
prototype_contracts <- read_excel("../data/prototype_contracts.xlsx")
contractor_categories <- readRDS("../data/contractor_categories.RDS")
contract_demographics <- readRDS("../data/contract_demographics.rds")

#read in unique patients
unique_patients_static <- readRDS("../data/unique_patients/unique_patients_static.rds")
unique_patients_rolling <- readRDS("../data/unique_patients/unique_patients_rolling.rds")

#read in recalls 
readRDS("../data/recalls/dental_recalls_2021_22.rds")

#evaluate chunks based on pack level
if(params$level == "National"){
  evaluate_contents_1 <- TRUE
  evaluate_contents_2 <- FALSE
  evaluate_regional <- TRUE
  evaluate_STP <- FALSE
  evaluate_111 <- TRUE
}else if(params$level == "Regional"){
  evaluate_contents_1 <- TRUE
  evaluate_contents_2 <- FALSE
  evaluate_regional <- FALSE
  evaluate_STP <- TRUE
  evaluate_111 <- FALSE
}else{
  evaluate_contents_1 <- FALSE
  evaluate_contents_2 <- TRUE
  evaluate_regional <- FALSE
  evaluate_STP <- FALSE
  evaluate_111 <- FALSE
}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#avoid standard form
options(scipen=999)


```




### UDA activity data 

 <font size="2">
 
 
```{r echo = FALSE, warning = FALSE, message = FALSE, fig.width=14, fig.height=5}

data <- plot_UDA_UOA_delivery_calendar(plotChart = F, STP_lines = T)

data %>%
  download_this(
    output_name = "UDA_delivery_calendar_data",
    output_extension = ".xlsx",
    button_label = "Download data",
    button_type = "warning",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```
 
```{r UDA_activity_Calendar, echo = FALSE, warning = FALSE, message = FALSE, fig.width=14, fig.height=5}
reactable(
  plot_UDA_UOA_delivery_calendar(plotChart = F, STP_lines = T),
  filterable = TRUE,
  paginateSubRows = TRUE,
  minRows = 5,
  highlight = TRUE,
  groupBy = c("Month","Region Name"),
  columns = list(
    `Monthly UDAs delivered`= colDef(aggregate = "sum", format = colFormat(digits = 0), filterable = FALSE),
    `Annual contracted UDAs` = colDef(aggregate = "sum", format = colFormat(digits = 0), filterable = FALSE),
    `Scaled monthly UDAs delivered` = colDef(aggregate = "sum", format = colFormat(digits = 0), filterable = FALSE),
    `Scaled percentage of UDAs delivered` = colDef(aggregate = "mean", format = colFormat(suffix = "%", digits = 1), filterable = FALSE)
  )
)
```


